### ISSUE TITLE
新建一个数据库表就要删整个库？

### ISSUE THREAD

**Issue by OhnkytaBlabdey** [OhnkytaBlabdey/SagumeAutomata#1]
https://github.com/OhnkytaBlabdey/SagumeAutomata/blob/a51e28a072397db69c438ea96c961a8f5fc3f7f5/src/DBHandler/index.ts#L82

触发数据库不存在的异常，才能执行初始化？ 🤔

**Comment by NeWive** [comment]
👴改还不行吗

**Comment by NeWive** [comment]
完成更新api，考虑使用commandline program的形式实现更新
